/** Curated pool used to power the skill suggestions/autocomplete on the Resume/CV details panel. */
export const SKILL_KEYWORDS: string[] = [
  "Content Strategy",
  "Digital Marketing",
  "Google Ads",
  "Press Releases",
  "Social Media Measurement",
  "Time Management",
  "Journalism",
  "Newsletters",
  "Pinterest Marketing",
  "Microsoft Excel",
  "Keyword Finder",
  "Keyword Autocomplete",
  "SEO",
  "Copywriting",
  "Email Marketing",
  "Project Management",
  "Public Speaking",
  "Graphic Design",
  "React",
  "TypeScript",
  "JavaScript",
  "Node.js",
  "Python",
  "Data Analysis",
  "UI/UX Design",
  "Figma",
  "Adobe Photoshop",
  "Video Editing",
  "Sales",
  "Customer Service",
  "Leadership",
  "Negotiation",
  "Budgeting",
  "Market Research",
  "Brand Strategy",
  "Community Management",
  "Google Analytics",
  "A/B Testing",
];
