import type { DesignState } from "@/store/slices/designSlice";

export interface StylePreset {
  key: string;
  label: string;
  locked?: boolean;
  values: Partial<Omit<DesignState, "dirty">>;
}

/**
 * One-click style presets — each bundles a whole set of design fields
 * (colors, wallpaper, header layout, fonts…) so picking one restyles the
 * entire card at once, instead of tuning every panel by hand.
 */
export const STYLE_PRESETS: StylePreset[] = [
  {
    key: "classic",
    label: "Classic",
    values: {
      primary: "#BE5103",
      accent: "#069494",
      theme: "light",
      wallpaperType: "fill",
      backgroundColor: "#FFFFFF",
      headerLayout: "classic",
      buttonColor: "#111111",
      buttonTextColor: "#FFFFFF",
      buttonStyle: "solid",
      buttonRoundness: "slight",
      buttonShadow: "none",
      socialLinksStyle: "buttons",
      pageFont: "Inter",
      pageTextColor: "#111111",
      matchTitleFont: true,
      titleFont: "Inter",
      titleColor: "#111111",
      titleFontSize: 20,
      bioFontSize: 12,
      bodyFontSize: 12,
    },
  },
  {
    key: "aura",
    label: "Aura",
    values: {
      primary: "#8B7FD1",
      accent: "#C9A9E0",
      theme: "light",
      wallpaperType: "gradient",
      gradientColor: "#B8AEDC",
      gradientColorEnd: "#DCD3E8",
      gradientDirection: "down",
      headerLayout: "hero",
      buttonColor: "#FFFFFF",
      buttonTextColor: "#3D3552",
      buttonStyle: "glass",
      buttonRoundness: "full",
      buttonShadow: "soft",
      socialLinksStyle: "icons",
      pageFont: "Inter",
      pageTextColor: "#3D3552",
      matchTitleFont: false,
      titleFont: "Playfair Display",
      titleColor: "#2B2440",
      titleFontSize: 28,
      bioFontSize: 13,
      bodyFontSize: 12,
    },
  },
  {
    key: "sunset",
    label: "Sunset",
    values: {
      primary: "#FF6A3D",
      accent: "#FFB400",
      theme: "light",
      wallpaperType: "gradient",
      gradientColor: "#FF8A5B",
      gradientColorEnd: "#FFD36E",
      gradientDirection: "up",
      headerLayout: "banner",
      buttonColor: "#FFFFFF",
      buttonTextColor: "#7A2E00",
      buttonStyle: "solid",
      buttonRoundness: "medium",
      buttonShadow: "strong",
      socialLinksStyle: "buttons",
      pageFont: "Poppins",
      pageTextColor: "#7A2E00",
      matchTitleFont: true,
      titleFont: "Poppins",
      titleColor: "#7A2E00",
      titleFontSize: 22,
      bioFontSize: 13,
      bodyFontSize: 13,
    },
  },
  {
    key: "noir",
    label: "Noir",
    values: {
      primary: "#1A1A1A",
      accent: "#8C8C8C",
      theme: "dark",
      wallpaperType: "image",
      // Placeholder photo — swap for an uploaded background once wallpaper
      // image upload exists; this just demonstrates the "image" wallpaper.
      backgroundImageUrl: "https://picsum.photos/seed/clickcard-noir/720/1280",
      headerLayout: "classic",
      buttonColor: "#000000",
      buttonTextColor: "#FFFFFF",
      buttonStyle: "glass",
      buttonRoundness: "slight",
      buttonShadow: "soft",
      socialLinksStyle: "icons",
      pageFont: "Inter",
      pageTextColor: "#FFFFFF",
      matchTitleFont: false,
      titleFont: "Anton",
      titleColor: "#FFFFFF",
      titleFontSize: 26,
      bioFontSize: 13,
      bodyFontSize: 12,
    },
  },
  {
    key: "botanica",
    label: "Botanica",
    values: {
      primary: "#3F5D3A",
      accent: "#B8C9A8",
      theme: "dark",
      wallpaperType: "image",
      backgroundImageUrl: "https://picsum.photos/seed/clickcard-botanica/720/1280",
      headerLayout: "banner",
      buttonColor: "#FFFFFF",
      buttonTextColor: "#234026",
      buttonStyle: "solid",
      buttonRoundness: "full",
      buttonShadow: "none",
      socialLinksStyle: "buttons",
      pageFont: "DM Sans",
      pageTextColor: "#FFFFFF",
      matchTitleFont: true,
      titleFont: "DM Sans",
      titleColor: "#FFFFFF",
      titleFontSize: 24,
      bioFontSize: 13,
      bodyFontSize: 12,
    },
  },
];
